add dot match in metadata
commonmark/commonmark-java pull request #191
Opened 2020-11-18 06:37 UTC by javaor

Sometimes we will have **a.b** in metadata, wish it will be support.

e.g. Below format:
---
ms.author: <author>
ms.date: yyyy/MM/dd
---

2020-11-26 04:55 UTC, robinst commented
Hey! Change makes sense to me, as YAML also supports dots within plain (unquoted) keys.

Can you add a test case for this though? Should be simple to add, see `YamlFrontMatterTest`.

2020-11-26 04:55 UTC, robinst requested changes
Please add a test

2020-12-08 09:06 UTC, javaor commented
Due to the change hasn't been merged, so the test case failed I think.

2020-12-09 00:26 UTC, merged

2020-12-09 00:26 UTC, robinst commented
Thanks! Will be in the next release 🔜